# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: admin

# Also define 'vault_users' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      # - https://github.com/username.keys
      - https://github.com/GarrettWeinberg.keys
      - https://github.com/MikaCaldera.keys
      - https://github.com/cjdias11.keys
      - https://github.com/MWDelaney.keys
      - https://github.com/Rob-Voss.keys
      - https://github.com/tbcsheldon.keys
  - name: "{{ admin_user }}"
    groups:
      - sudo
    keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      # - https://github.com/username.keys
      - https://github.com/GarrettWeinberg.keys
      - https://github.com/MikaCaldera.keys
      - https://github.com/cjdias11.keys
      - https://github.com/MWDelaney.keys
      - https://github.com/Rob-Voss.keys
      - https://github.com/tbcsheldon.keys

web_user: web
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php{{ php_version }}-fpm *"
